// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoeZ7yiSg0vAsr6zofGU0b9z86QFW0bDg',
    appId: '1:823950096800:web:49e88b928fcf7eb10e4cc5',
    messagingSenderId: '823950096800',
    projectId: 'bikethievesarejerks',
    authDomain: 'bikethievesarejerks.firebaseapp.com',
    storageBucket: 'bikethievesarejerks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWWqHWMzppl8Fk3UsnNbPgYRguQUYyuE',
    appId: '1:823950096800:android:bb5d236c89b015bf0e4cc5',
    messagingSenderId: '823950096800',
    projectId: 'bikethievesarejerks',
    storageBucket: 'bikethievesarejerks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFBw4GyNX_OGMzuespQ_PYFaRHZV4gLk',
    appId: '1:823950096800:ios:41e85fde6b644dfc0e4cc5',
    messagingSenderId: '823950096800',
    projectId: 'bikethievesarejerks',
    storageBucket: 'bikethievesarejerks.firebasestorage.app',
    iosBundleId: 'com.hoangyennguyen2.bleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVFBw4GyNX_OGMzuespQ_PYFaRHZV4gLk',
    appId: '1:823950096800:ios:12e9ec7072df4cca0e4cc5',
    messagingSenderId: '823950096800',
    projectId: 'bikethievesarejerks',
    storageBucket: 'bikethievesarejerks.firebasestorage.app',
    iosBundleId: 'com.example.bleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoeZ7yiSg0vAsr6zofGU0b9z86QFW0bDg',
    appId: '1:823950096800:web:7dcff91ff54309fe0e4cc5',
    messagingSenderId: '823950096800',
    projectId: 'bikethievesarejerks',
    authDomain: 'bikethievesarejerks.firebaseapp.com',
    storageBucket: 'bikethievesarejerks.firebasestorage.app',
  );
}
